:grinning:=😀
:smiley:=😃
:smile:=😄
:grin:=😁
:laughing:=😆
:sweat_smile:=😅
:rofl:=🤣
:joy:=😂
:slight_smile:=🙂
:upside_down:=🙃
:melting_face:=🫠
:wink:=😉
:blush:=😊
:innocent:=😇
:smiling_face_with_3_hearts:=🥰
:heart_eyes:=😍
:star_struck:=🤩
:kissing_heart:=😘
:kissing:=😗
:relaxed:=☺
:kissing_closed_eyes:=😚
:kissing_smiling_eyes:=😙
:smiling_face_with_tear:=🥲
:yum:=😋
:stuck_out_tongue:=😛
:stuck_out_tongue_winking_eye:=😜
:zany_face:=🤪
:stuck_out_tongue_closed_eyes:=😝
:money_mouth_face:=🤑
:hugging:=🤗
:hand_over_mouth:=🤭
:face_with_peeking_eye:=🫢
:face_with_hand_over_mouth:=🫣
:shushing_face:=🤫
:thinking:=🤔
:saluting_face:=🫡
:zipper_mouth:=🤐
:face_with_raised_eyebrow:=🤨
:neutral_face:=😐
:expressionless:=😑
:no_mouth:=😶
:face_dotted_line:=🫥
:smirk:=😏
:unamused:=😒
:roll_eyes:=🙄
:grimacing:=😬
:lying_face:=🤥
:shaking_face:=🫨
:relieved:=😌
:pensive:=😔
:sleepy:=😪
:drooling_face:=🤤
:sleeping:=😴
:paper_plane:=🫩
:mask:=😷
:face_with_thermometer:=🤒
:face_with_head_bandage:=🤕
:nauseated_face:=🤢
:vomiting_face:=🤮
:sneezing_face:=🤧
:hot_face:=🥵
:cold_face:=🥶
:woozy_face:=🥴
:dizzy_face:=😵
:exploding_head:=🤯
:cowboy:=🤠
:partying_face:=🥳
:disguised_face:=🥸
:sunglasses:=😎
:nerd:=🤓
:monocle:=🧐
:confused:=😕
:face_with_diagonal_mouth:=🫤
:worried:=😟
:slight_frown:=🙁
:frowning2:=☹
:open_mouth:=😮
:hushed:=😯
:astonished:=😲
:flushed:=😳
:pleading_face:=🥺
:face_holding_back_tears:=🥹
:frowning:=😦
:anguished:=😧
:fearful:=😨
:cold_sweat:=😰
:disappointed_relieved:=😥
:cry:=😢
:sob:=😭
:scream:=😱
:confounded:=😖
:persevere:=😣
:disappointed:=😞
:sweat:=😓
:weary:=😩
:tired_face:=😫
:yawning_face:=🥱
:triumph:=😤
:rage:=😡
:angry:=😠
:cursing_face:=🤬
:smiling_imp:=😈
:imp:=👿
:skull:=💀
:skull_and_crossbones:=☠
:poop:=💩
:clown:=🤡
:japanese_ogre:=👹
:japanese_goblin:=👺
:ghost:=👻
:alien:=👽
:space_invader:=👾
:robot:=🤖
:smiley_cat:=😺
:smile_cat:=😸
:joy_cat:=😹
:heart_eyes_cat:=😻
:smirk_cat:=😼
:kissing_cat:=😽
:scream_cat:=🙀
:crying_cat_face:=😿
:pouting_cat:=😾
:see_no_evil:=🙈
:hear_no_evil:=🙉
:speak_no_evil:=🙊
:love_letter:=💌
:cupid:=💘
:gift_heart:=💝
:sparkling_heart:=💖
:heartpulse:=💗
:heartbeat:=💓
:revolving_hearts:=💞
:two_hearts:=💕
:heart_decoration:=💟
:exclamation:=❣
:broken_heart:=💔
:heart:=❤
:pink_heart:=🩷
:orange_heart:=🧡
:yellow_heart:=💛
:green_heart:=💚
:blue_heart:=💙
:light_blue_heart:=🩵
:purple_heart:=💜
:brown_heart:=🤎
:black_heart:=🖤
:grey_heart:=🩶
:white_heart:=🤍
:kiss:=💋
:100:=💯
:anger:=💢
:boom:=💥
:dizzy:=💫
:sweat_drops:=💦
:dash:=💨
:hole:=🕳
:speech_balloon:=💬
:left_speech_bubble:=🗨
:right_anger_bubble:=🗯
:thought_balloon:=💭
:zzz:=💤
:wave:=👋
:raised_back_of_hand:=🤚
:raised_hand_with_fingers_splayed:=🖐
:hand:=✋
:vulcan:=🖖
:right_hand:=🫱
:left_hand:=🫲
:palm_down_hand:=🫳
:palm_up_hand:=🫴
:rightwards_pushing_hand:=🫷
:leftwards_pushing_hand:=🫸
:ok_hand:=👌
:pinched_fingers:=🤌
:pinching_hand:=🤏
:v:=✌
:crossed_fingers:=🤞
:hand_with_index_finger_and_thumb_crossed:=🫰
:love_you_gesture:=🤟
:metal:=🤘
:call_me:=🤙
:point_left:=👈
:point_right:=👉
:point_up_2:=👆
:middle_finger:=🖕
:point_down:=👇
:point_up:=☝
:index_pointing_at_the_viewer:=🫵
:thumbsup:=👍
:thumbsdown:=👎
:fist:=✊
:punch:=👊
:left_facing_fist:=🤛
:right_facing_fist:=🤜
:clap:=👏
:raised_hands:=🙌
:heart_hands:=🫶
:open_hands:=👐
:palms_up_together:=🤲
:handshake:=🤝
:pray:=🙏
:writing_hand:=✍
:nail_care:=💅
:selfie:=🤳
:muscle:=💪
:mechanical_arm:=🦾
:mechanical_leg:=🦿
:leg:=🦵
:foot:=🦶
:ear:=👂
:ear_with_hearing_aid:=🦻
:nose:=👃
:brain:=🧠
:anatomical_heart:=🫀
:lungs:=🫁
:tooth:=🦷
:bone:=🦴
:eyes:=👀
:eye:=👁
:tongue:=👅
:mouth:=👄
:biting_lip:=🫦
:speaking_head:=🗣
:bust_in_silhouette:=👤
:busts_in_silhouette:=👥
:people_holding_hands:=🫂
:family:=👪
:feet:=👣
:pregnant_man:=🫆
:red_hair:=🦰
:curly_hair:=🦱
:white_hair:=🦳
:bald:=🦲
:monkey_face:=🐵
:monkey:=🐒
:gorilla:=🦍
:orangutan:=🦧
:dog:=🐶
:dog2:=🐕
:guide_dog:=🦮
:poodle:=🐩
:wolf:=🐺
:fox:=🦊
:raccoon:=🦝
:cat:=🐱
:cat2:=🐈
:lion:=🦁
:tiger:=🐯
:frog:=🐸
:crocodile:=🐊
:turtle:=🐢
:lizard:=🦎
:snake:=🐍
:dragon_face:=🐲
:dragon:=🐉
:sauropod:=🦕
:t_rex:=🦖
:bouquet:=💐
:cherry_blossom:=🌸
:white_flower:=💮
:lotus:=🪷
:rosette:=🏵
:rose:=🌹
:wilted_flower:=🥀
:hibiscus:=🌺
:sunflower:=🌻
:blossom:=🌼
:tulip:=🌷
:hyacinth:=🪻
:bread:=🍞
:croissant:=🥐
:baguette_bread:=🥖
:flatbread:=🫓
:pretzel:=🥨
:bagel:=🥯
:pancakes:=🥞
:waffle:=🧇
:cheese:=🧀
:meat_on_bone:=🍖
:poultry_leg:=🍗
:cut_of_meat:=🥩
:bacon:=🥓
:hamburger:=🍔
:fries:=🍟
:pizza:=🍕
:hotdog:=🌭
:sandwich:=🥪
:taco:=🌮
:burrito:=🌯
:tamale:=🫔
:stuffed_flatbread:=🥙
:falafel:=🧆
:egg:=🥚
:fried_egg:=🍳
:shallow_pan_of_food:=🥘
:stew:=🍲
:fondue:=🫕
:bowl_with_spoon:=🥣
:salad:=🥗
:popcorn:=🍿
:butter:=🧈
:salt:=🧂
:canned_food:=🥫
:anchor:=⚓
:life_saver:=🛟
:sailboat:=⛵
:canoe:=🛶
:speedboat:=🚤
:passenger_ship:=🛳
:ferry:=⛴
:motor_boat:=🛥
:ship:=🚢
:airplane:=✈
:small_airplane:=🛩
:flight_departure:=🛫
:flight_arrival:=🛬
:parachute:=🪂
:seat:=💺
:helicopter:=🚁
:suspension_railway:=🚟
:mountain_cableway:=🚠
:aerial_tramway:=🚡
:satellite:=🛰
:rocket:=🚀
:flying_saucer:=🛸
:bellhop_bell:=🛎
:luggage:=🧳
:hourglass:=⌛
:hourglass_flowing_sand:=⏳
:watch:=⌚
:alarm_clock:=⏰
:stopwatch:=⏱
:timer:=⏲
:clock:=🕰
:clock12:=🕛
:clock1230:=🕧
:clock1:=🕐
:clock130:=🕜
:clock2:=🕑
:clock230:=🕝
:clock3:=🕒
:clock330:=🕞
:clock4:=🕓
:clock430:=🕟
:clock5:=🕔
:clock530:=🕠
:clock6:=🕕
:clock630:=🕡
:clock7:=🕖
:clock730:=🕢
:clock8:=🕗
:clock830:=🕣
:clock9:=🕘
:clock930:=🕤
:clock10:=🕙
:clock1030:=🕥
:clock11:=🕚
:clock1130:=🕦
:new_moon:=🌑
:waxing_crescent_moon:=🌒
:first_quarter_moon:=🌓
:waxing_gibbous_moon:=🌔
:full_moon:=🌕
:waning_gibbous_moon:=🌖
:last_quarter_moon:=🌗
:waning_crescent_moon:=🌘
:moon:=🌙
:new_moon_with_face:=🌚
:first_quarter_moon_with_face:=🌛
:last_quarter_moon_with_face:=🌜
:thermometer:=🌡
:sun:=☀
:full_moon_with_face:=🌝
:sun_with_face:=🌞
:ringed_planet:=🪐
:star:=⭐
:star2:=🌟
:milky_way:=🌠
:cloud:=🌌
:cloud:=☁
:partly_sunny:=⛅
:cloud_with_lightning_and_rain:=⛈
:sun_behind_small_cloud:=🌤
:sun_behind_cloud:=🌥
:sun_behind_rain_cloud:=🌦
:cloud_with_rain:=🌧
:cloud_with_lightning:=🌩
:tornado:=🌪
:fog:=🌫
:wind_face:=🌬
:cyclone:=🌀
:rainbow:=🌈
:closed_umbrella:=🌂
:umbrella:=☂
:umbrella_with_rain_drops:=☔
:beach_umbrella:=⛱
:zap:=⚡
:snowflake:=❄
:snowman:=☃
:snowman_without_snow:=⛄
:comet:=☄
:fire:=🔥
:droplet:=💧
:ocean:=🌊
:military_medal:=🎖
:trophy:=🏆
:medal:=🏅
:gold_medal:=🥇
:silver_medal:=🥈
:bronze_medal:=🥉
:soccer:=⚽
:baseball:=⚾
:softball:=🥎
:basketball:=🏀
:volleyball:=🏐
:football:=🏈
:rugby_football:=🏉
:tennis:=🎾
:flying_disc:=🥏
:bowling:=🎳
:cricket_game:=🏏
:field_hockey:=🏑
:ice_hockey:=🏒
:lacrosse:=🥍
:ping_pong:=🏓
:badminton:=🏸
:boxing_glove:=🥊
:martial_arts_uniform:=🥋
:goal_net:=🥅
:golf:=⛳
:ice_skate:=⛸
:fishing_pole_and_fish:=🎣
:diving_mask:=🤿
:running_shirt_with_sash:=🎽
:ski:=🎿
:sled:=🛷
:curling_stone:=🥌
:jack_o_lantern:=🎃
:christmas_tree:=🎄
:fireworks:=🎆
:sparkler:=🎇
:firecracker:=🧨
:sparkles:=✨
:balloon:=🎈
:tada:=🎉
:confetti_ball:=🎊
:tanabata_tree:=🎋
:bamboo:=🎍
:dolls:=🎎
:flags:=🎏
:wind_chime:=🎐
:moon_viewing_ceremony:=🎑
:red_envelope:=🧧
:ribbon:=🎀
:gift:=🎁
:reminder_ribbon:=🎗
:ticket:=🎟
:tickets:=🎫
:red_circle:=🔴
:orange_circle:=🟠
:yellow_circle:=🟡
:green_circle:=🟢
:blue_circle:=🔵
:purple_circle:=🟣
:brown_circle:=🟤
:black_circle:=⚫
:white_circle:=⚪
:red_square:=🟥
:orange_square:=🟧
:yellow_square:=🟨
:green_square:=🟩
:blue_square:=🟦
:purple_square:=🟪
:brown_square:=🟫
:black_large_square:=⬛
:white_large_square:=⬜
:black_medium_square:=◼
:white_medium_square:=◻
:black_medium_small_square:=◾
:white_medium_small_square:=◽
:black_small_square:=▪
:white_small_square:=▫
:large_orange_diamond:=🔶
:large_blue_diamond:=🔷
:small_orange_diamond:=🔸
:small_blue_diamond:=🔹
:red_triangle_up:=🔺
:red_triangle_down:=🔻
:diamond_shape_with_a_dot_inside:=💠
:radio_button:=🔘
:white_square_button:=🔳
:black_square_button:=🔲
:checkered_flag:=🏁
:triangular_flag_on_post:=🚩
:crossed_flags:=🎌
:black_flag:=🏴
:white_flag:=🏳